/**
 * Shared helpers for reading and writing the LocalHost monthly Excel template.
 *
 * The template itself is generated by scripts/generate_simple_monthly_template.py.
 * Cell coordinates below MUST stay in sync with that generator — if the layout
 * changes, update both places.
 */

import { readFile } from 'node:fs/promises';
import path from 'node:path';
import ExcelJS from 'exceljs';

import { MONTH_NAMES } from '@/lib/constants';

export const TEMPLATE_PATH = path.join(
  process.cwd(),
  'public',
  'assets',
  'LocalHost_Monthly_Template_Simple.xlsx',
);

export const XLSX_MIME =
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

// ── Dashboard meta cells ────────────────────────────────────────────
export const DASHBOARD = {
  apartmentName: 'B6',
  month: 'E6',
  preparedBy: 'H6',
  registrationId: 'B9',
  submissionDate: 'E9',
  contact: 'H9',
};

// Roster on Dashboard (8 slots).
export const ROSTER = {
  firstRow: 14,
  lastRow: 21,
  cols: {
    name: 'C',
    email: 'D',
    status: 'E',
    role: 'F',
    phone: 'G',
  },
};

// Meals sheet layout (per the generator: 2 slots, 8 members, 31 days).
export const MEALS = {
  // First section (slot 0)
  slot0: {
    sectionRow: 5,
    headerRow: 7,
    firstDataRow: 8,
    lastDataRow: 38,
    totalRow: 39,
  },
  // Second section (slot 1)
  slot1: {
    sectionRow: 41,
    headerRow: 43,
    firstDataRow: 44,
    lastDataRow: 74,
    totalRow: 75,
  },
  // Member columns are C..J (3..10) for 8 members; K is per-day total.
  memberFirstColIndex: 3,
  memberLastColIndex: 10,
  dayColIndex: 2, // B
};

// Costs sheet layout (per the generator).
export const COSTS = {
  market: {
    firstRow: 7,
    lastRow: 30,
    totalRow: 31,
    cols: {
      date: 'B',
      item: 'C',
      quantity: 'D',
      amount: 'E',
      boughtBy: 'F',
      receipt: 'G',
      notes: 'H',
    },
  },
  fixed: {
    firstRow: 35,
    lastRow: 46,
    totalRow: 47,
    cols: {
      item: 'B',
      amount: 'C',
      paidBy: 'D',
      paymentMethod: 'E',
      reference: 'F',
      dueDate: 'G',
      notes: 'H',
    },
  },
  bill: {
    electricityUnits: 'C50',
    electricityAmount: 'F50',
    adjFirstRow: 53,
    adjLastRow: 60,
    cols: {
      memberEmail: 'B',
      type: 'C',
      label: 'D',
      amount: 'E',
      createdBy: 'F',
      date: 'G',
      notes: 'H',
    },
  },
  other: {
    firstRow: 64,
    lastRow: 87,
    totalRow: 88,
    cols: {
      date: 'B',
      category: 'C',
      description: 'D',
      boughtBy: 'E',
      amount: 'F',
      paymentMethod: 'G',
      notes: 'H',
    },
  },
};

// ── Types we use from the database ──────────────────────────────────

export type ApartmentMeta = {
  name: string;
  registrationId: string;
  adminMemberId?: string | null;
  billManagerId?: string | null;
} | null;

export type RosterMember = {
  id: string;
  name: string;
  email?: string | null;
  phone?: string | null;
};

export type PreparedBy = {
  name?: string | null;
  email?: string | null;
  phone?: string | null;
} | null;

export type MealRecordRow = {
  memberId: string;
  mealDate: Date;
  mealSlot: number;
};

export type MealShoppingRow = {
  itemName: string;
  amount: number;
  purchaseDate: Date;
  memberId: string;
};

export type FixedCostRow = {
  name: string;
  amount: number;
};

export type BillSnapshot = {
  electricity?: number | null;
} | null;

export type AdjustmentRow = {
  memberId: string;
  type: string;
  label: string;
  amount: number;
  createdBy?: string | null;
  createdAt: Date;
};

export type ExpenseRow = {
  itemName: string;
  price: number;
  category: string;
  expenseDate?: Date | null;
  memberId: string;
};

// ── Utilities ───────────────────────────────────────────────────────

export function slugify(input: string, fallback: string): string {
  const slug = input
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
  return slug || fallback;
}

export function monthLabelOf(monthKey: string): string {
  const [year, mm] = monthKey.split('-');
  const idx = Number(mm) - 1;
  return `${MONTH_NAMES[idx] ?? ''} ${year}`.trim();
}

export async function loadWorkbook(): Promise<ExcelJS.Workbook> {
  const buffer = await readFile(TEMPLATE_PATH);
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(buffer);
  return wb;
}

export async function workbookToBuffer(wb: ExcelJS.Workbook): Promise<Buffer> {
  const data = await wb.xlsx.writeBuffer();
  return Buffer.from(data);
}

// ── Fillers ─────────────────────────────────────────────────────────

export function fillDashboardMeta(
  wb: ExcelJS.Workbook,
  args: {
    apartment: ApartmentMeta;
    monthKey: string;
    preparedBy?: PreparedBy;
    submissionDate?: Date;
  },
): void {
  const ws = wb.getWorksheet('Dashboard');
  if (!ws) return;

  if (args.apartment?.name) ws.getCell(DASHBOARD.apartmentName).value = args.apartment.name;
  if (args.apartment?.registrationId) {
    ws.getCell(DASHBOARD.registrationId).value = args.apartment.registrationId;
  }

  ws.getCell(DASHBOARD.month).value = monthLabelOf(args.monthKey);

  if (args.submissionDate) {
    const cell = ws.getCell(DASHBOARD.submissionDate);
    cell.value = args.submissionDate;
    cell.numFmt = 'yyyy-mm-dd';
  }

  if (args.preparedBy?.name) {
    ws.getCell(DASHBOARD.preparedBy).value = args.preparedBy.name;
  }
  const contact = [args.preparedBy?.phone, args.preparedBy?.email]
    .filter(Boolean)
    .join('  ·  ');
  if (contact) ws.getCell(DASHBOARD.contact).value = contact;
}

export function fillRoster(
  wb: ExcelJS.Workbook,
  args: {
    members: RosterMember[];
    apartment: ApartmentMeta;
  },
): void {
  const ws = wb.getWorksheet('Dashboard');
  if (!ws) return;
  const adminId = args.apartment?.adminMemberId;
  const billManagerId = args.apartment?.billManagerId;
  args.members.forEach((m, idx) => {
    const row = ROSTER.firstRow + idx;
    if (row > ROSTER.lastRow) return;
    ws.getCell(`${ROSTER.cols.name}${row}`).value = m.name || '';
    ws.getCell(`${ROSTER.cols.email}${row}`).value = m.email || '';
    ws.getCell(`${ROSTER.cols.status}${row}`).value = 'Active';
    const role =
      adminId === m.id
        ? 'Admin'
        : billManagerId === m.id
          ? 'Bill Manager'
          : 'Member';
    ws.getCell(`${ROSTER.cols.role}${row}`).value = role;
    if (m.phone) ws.getCell(`${ROSTER.cols.phone}${row}`).value = m.phone;
  });
}

/** Update visible slot section titles to match the apartment's meal config. */
export function fillMealSlotLabels(
  wb: ExcelJS.Workbook,
  mealNames: string[],
): void {
  const ws = wb.getWorksheet('Meals');
  if (!ws) return;
  const labels: [number, string][] = [
    [MEALS.slot0.sectionRow, (mealNames[0] || 'Lunch').toUpperCase()],
    [MEALS.slot1.sectionRow, (mealNames[1] || 'Dinner').toUpperCase()],
  ];
  for (const [row, label] of labels) {
    ws.getCell(`B${row}`).value = label;
  }
}

export function fillMealsGrid(
  wb: ExcelJS.Workbook,
  args: {
    members: RosterMember[];
    monthKey: string;
    records: MealRecordRow[];
  },
): void {
  const ws = wb.getWorksheet('Meals');
  if (!ws) return;

  const memberIndex = new Map<string, number>();
  args.members.forEach((m, idx) => {
    if (idx < MEALS.memberLastColIndex - MEALS.memberFirstColIndex + 1) {
      memberIndex.set(m.id, idx);
    }
  });

  // Build a key -> count map (slot, memberIndex, day) so multiple records on
  // the same day for the same slot just stack as +1.
  const counts = new Map<string, number>();
  for (const r of args.records) {
    const mi = memberIndex.get(r.memberId);
    if (mi === undefined) continue;
    const slotIdx = r.mealSlot >= 1 ? 1 : 0; // template fits 2 slots
    const day = r.mealDate.getUTCDate();
    if (day < 1 || day > 31) continue;
    const key = `${slotIdx}|${mi}|${day}`;
    counts.set(key, (counts.get(key) || 0) + 1);
  }

  const writeSlot = (slotKey: 'slot0' | 'slot1', slotIdx: number) => {
    const layout = MEALS[slotKey];
    for (let day = 1; day <= 31; day++) {
      const row = layout.firstDataRow + (day - 1);
      for (let mi = 0; mi < args.members.length; mi++) {
        if (mi > MEALS.memberLastColIndex - MEALS.memberFirstColIndex) break;
        const col = MEALS.memberFirstColIndex + mi;
        const v = counts.get(`${slotIdx}|${mi}|${day}`);
        if (v) ws.getRow(row).getCell(col).value = v;
      }
    }
  };
  writeSlot('slot0', 0);
  writeSlot('slot1', 1);
}

export function fillMarket(
  wb: ExcelJS.Workbook,
  args: {
    rows: MealShoppingRow[];
    memberById: Map<string, RosterMember>;
  },
): void {
  const ws = wb.getWorksheet('Costs');
  if (!ws) return;
  const { firstRow, lastRow, cols } = COSTS.market;
  args.rows.slice(0, lastRow - firstRow + 1).forEach((m, idx) => {
    const r = firstRow + idx;
    const date = ws.getCell(`${cols.date}${r}`);
    date.value = m.purchaseDate;
    date.numFmt = 'yyyy-mm-dd';
    ws.getCell(`${cols.item}${r}`).value = m.itemName;
    const amt = ws.getCell(`${cols.amount}${r}`);
    amt.value = m.amount;
    amt.numFmt = '#,##0.00';
    const member = args.memberById.get(m.memberId);
    if (member?.email) {
      ws.getCell(`${cols.boughtBy}${r}`).value = member.email;
    } else if (member?.name) {
      ws.getCell(`${cols.boughtBy}${r}`).value = member.name;
    }
  });
}

export function fillFixedCosts(
  wb: ExcelJS.Workbook,
  args: { rows: FixedCostRow[] },
): void {
  const ws = wb.getWorksheet('Costs');
  if (!ws) return;
  const { firstRow, lastRow, cols } = COSTS.fixed;
  args.rows.slice(0, lastRow - firstRow + 1).forEach((c, idx) => {
    const r = firstRow + idx;
    ws.getCell(`${cols.item}${r}`).value = c.name;
    const amt = ws.getCell(`${cols.amount}${r}`);
    amt.value = c.amount;
    amt.numFmt = '#,##0.00';
  });
}

export function fillBill(
  wb: ExcelJS.Workbook,
  args: {
    bill: BillSnapshot;
    adjustments: AdjustmentRow[];
    memberById: Map<string, RosterMember>;
  },
): void {
  const ws = wb.getWorksheet('Costs');
  if (!ws) return;
  if (typeof args.bill?.electricity === 'number') {
    const cell = ws.getCell(COSTS.bill.electricityUnits);
    cell.value = args.bill.electricity;
    cell.numFmt = '#,##0';
  }
  const { adjFirstRow, adjLastRow, cols } = COSTS.bill;
  args.adjustments.slice(0, adjLastRow - adjFirstRow + 1).forEach((a, idx) => {
    const r = adjFirstRow + idx;
    const member = args.memberById.get(a.memberId);
    if (member?.email) ws.getCell(`${cols.memberEmail}${r}`).value = member.email;
    else if (member?.name) ws.getCell(`${cols.memberEmail}${r}`).value = member.name;
    ws.getCell(`${cols.type}${r}`).value = a.type;
    ws.getCell(`${cols.label}${r}`).value = a.label;
    const amt = ws.getCell(`${cols.amount}${r}`);
    amt.value = a.amount;
    amt.numFmt = '#,##0.00';
    const date = ws.getCell(`${cols.date}${r}`);
    date.value = a.createdAt;
    date.numFmt = 'yyyy-mm-dd';
  });
}

export function fillExpenses(
  wb: ExcelJS.Workbook,
  args: {
    rows: ExpenseRow[];
    memberById: Map<string, RosterMember>;
  },
): void {
  const ws = wb.getWorksheet('Costs');
  if (!ws) return;
  const { firstRow, lastRow, cols } = COSTS.other;
  args.rows.slice(0, lastRow - firstRow + 1).forEach((e, idx) => {
    const r = firstRow + idx;
    if (e.expenseDate) {
      const date = ws.getCell(`${cols.date}${r}`);
      date.value = e.expenseDate;
      date.numFmt = 'yyyy-mm-dd';
    }
    ws.getCell(`${cols.category}${r}`).value = e.category;
    ws.getCell(`${cols.description}${r}`).value = e.itemName;
    const member = args.memberById.get(e.memberId);
    if (member?.email) ws.getCell(`${cols.boughtBy}${r}`).value = member.email;
    else if (member?.name) ws.getCell(`${cols.boughtBy}${r}`).value = member.name;
    const amt = ws.getCell(`${cols.amount}${r}`);
    amt.value = e.price;
    amt.numFmt = '#,##0.00';
  });
}
